//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkflowEngine
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WorkflowEngineEntities : DbContext
    {
        public WorkflowEngineEntities()
            : base("name=WorkflowEngineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountGroup> AccountGroup { get; set; }
        public virtual DbSet<AccountGroupMembers> AccountGroupMembers { get; set; }
        public virtual DbSet<Accounts> Accounts { get; set; }
        public virtual DbSet<wfDefaultApproverGroup> wfDefaultApproverGroup { get; set; }
        public virtual DbSet<wfDefaultApprovers> wfDefaultApprovers { get; set; }
        public virtual DbSet<wfDefinition> wfDefinition { get; set; }
        public virtual DbSet<wfStepPath> wfStepPath { get; set; }
        public virtual DbSet<wfSteps> wfSteps { get; set; }
    
        public virtual int Proc_NewTicket(string userid, string wfCode)
        {
            var useridParameter = userid != null ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(string));
    
            var wfCodeParameter = wfCode != null ?
                new ObjectParameter("wfCode", wfCode) :
                new ObjectParameter("wfCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_NewTicket", useridParameter, wfCodeParameter);
        }
    }
}
